### ISSUE TITLE
issue on node 11.10.0

### ISSUE THREAD

**Issue by josselinchevalay** [alanshaw/pull-stream-to-async-iterator#1]
when i try to use this project : https://github.com/ipfs/js-ipfs/tree/master/examples/run-in-electron

i have this issue : 

```
  return (async function * () {
                         ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/josselin/develop/migration-telescope/node_modules/async-iterator-to-pull-stream/index.js:2:20)
```

**Comment by lanmower** [comment]
me too :(

**Comment by rmisio** [comment]
I think the problem is because the code on npm is not ES5 and most people running Babel are not transpiling node_modules code (nor should they).

@alanshaw Could you please publish transpiled ES5 code to npm?

**Comment by rmisio** [comment]
FWIW, when I upgraded my node version from 9.8 to 11.10.1, I don't get this issue.

But... I 'm not sure modern browsers natively support async generators, so it's probably safer for the repo maintainer to publish transpiled code.

**Comment by alanshaw** [comment]
[Async generators have been supported in Node.js since v10](https://node.green/#ES2018-features-Asynchronous-Iterators-async-generators). Please upgrade from Node.js 8 - [it's no longer maintained](https://nodejs.org/en/about/releases/).
